export const LOAD_COUNTRIES = "LOAD_COUNTRIES";
export const SEARCH_COUNTRIES = "SEARCH_COUNTRIES";
export const FILTER_COUNTRIES_BY_REGION = "FILTER_COUNTRIES_BY_REGION";
export const SELECT_COUNTRY = "SELECT_COUNTRY";
export const CHANGE_PAGE = "CHANGE_PAGE";
